# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'photoram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  pod 'FirebaseUI/Auth', '~> 8.0'
  pod 'FirebaseUI/Email', '~> 8.0'
  pod 'FirebaseUI/Google', '~> 8.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
end
